#!/bin/bash

app \
    -provider=github \
    -upstream=$UPSTREAM_URL \
    --tls-cert=/usr/local/etc/server.crt \
    --tls-key=/usr/local/etc/server.key \
    -email-domain=* \
    -github-org=advizex \
    -github-team=${OAUTH_PROXY_GITHUB_TEAM:-two-factor-auth}
